[package]
name = "goldboot-image"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.8.4"
zstd = "0.9.0"
serde = { version="1",features = ["derive"] }
serde_json = "1"
validator = { version = "0.12", features = ["derive"] }
sha2 = "0.10.2"