[package]
name = "goldboot-image"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.8.4"
log = { version = "0.4.11", default-features = false }
serde = { version="1",features = ["derive"] }
serde_json = "1"
sha2 = "0.10.2"
validator = { version = "0.12", features = ["derive"] }
zstd = "0.9.0"