[package]
name = "goldboot-image"
description = "Defines the goldboot image format"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Tyler Cook"]
homepage = "https://goldboot.fossable.org"
repository = "https://github.com/fossable/goldboot"

[dependencies]
aes-gcm = { version = "0.10.3", features = ["std"] }
binrw = "0.13.1"
env_logger = "0.10.1"
flate2 = "1.0.28"
hex = "0.4.3"
log = { version = "0.4.20", default-features = false }
rand = "0.8.5"
regex = "1.10.2"
serde = { version = "1.0.193", features = ["derive"] }
sha2 = "0.10.8"
simple-error = "0.3.0"
strum = { version = "0.25.0", features = ["derive"] }
zstd = "0.13.0"

[dev-dependencies]
sha1 = "0.10.6"
tempfile = "3.8.1"
test-env-log = "0.2.8"
