[package]
name = "goldboot"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.14.0", features = ["exts"]}
uefi-services = { version = "0.11.0" }
log = { version = "0.4.11", default-features = false }
anyhow = { version = "1.0", default-features = false}
