# Configure ArchLinux with Ansible.

- hosts: localhost
  tasks:
    - name: Set hostname
      copy:
        dest: /etc/hostname
        content: |
          ArchLinux

    - name: Update package cache
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages
      package:
        name:
          - alacritty
          - cmus
          - curl
          - git
          - htop
          - jq
          - nano
          - nautilus
          - net-tools
          - nmap
          - ntp
          - openbsd-netcat
          - openssh
          - rsync
          - sshfs
          - tree
          - unzip
          - wget
          - zip
          - zsh
        state: latest
