[package]
name = "goldboot-linux"
description = "A minimal Linux distribution for deploying goldboot images"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Tyler Cook"]
readme = "README.md"
homepage = "https://goldboot.org"
repository = "https://github.com/goldboot/goldboot/"

[dependencies]
block-utils = "0.10.6"
env_logger = "0.9"
goldboot = { path="../goldboot", version = "0.0.1" }
gtk4 = "0.4.7"
gdk4 = "0.4.7"
gdk-pixbuf = "0.15.11"
glib-macros = "0.15.11"
log = { version = "0.4.11", default-features = false }
rust-embed = "6.3.0"
serde = { version="1",features = ["derive"] }
serde_json = "1"
ubyte = "0.10.1"