[package]
name = "goldboot-registry"
description = "A web service for hosting goldboot images"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Tyler Cook"]
readme = "README.md"
homepage = "https://goldboot.fossable.org"
repository = "https://github.com/fossable/goldboot"

[dependencies]
axum = "0.7.1"
env_logger = "0.10.0"
log = { version = "0.4.20", default-features = false }
reqwest = { version = "0.11.22", features = ["stream"] }
rustls = "0.21.8"
rustls-pemfile = "1.0.3"
simple-error = "0.3.0"
tokio = { version = "1.34.0", features = ["full"] }
goldboot = { path="../goldboot", version = "0.0.1" }
