[package]
name = "goldboot"
description = "A command-line application for building goldboot images"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Tyler Cook"]
readme = "README.md"
homepage = "https://goldboot.org"
repository = "https://github.com/goldboot/goldboot/"

[dependencies]
aes-gcm = { version = "0", features = ["std"] }
binrw = "0"
bzip2-rs = "0"
chrono = "0"
clap = { version = "3", features = ["derive"] }
colored = "2"
env_logger = "0"
flate2 = "1"
goldboot-graphics = { path="../goldboot-graphics", version = "0.0.1" }
hex = "0"
indicatif = "0"
log = { version = "0", default-features = false }
png = "0"
quick-xml = { version = "0", features = ["serialize"] }
rand = "0"
reqwest = { version = "0", features=["blocking", "stream", "json"] }
rust-embed = "6"
serde = { version="1", features = ["derive"] }
serde_json = "1"
sha1 = "0"
sha2 = "0"
simple-error = "0"
ssh2 = {version = "0", features = ["vendored-openssl"]}
tempfile = "3"
ubyte = "0"
validator = { version = "0", features = ["derive"] }
vnc = "0"
whoami = "1"
zstd = "^0.10"
regex = "1"

[dev-dependencies]
test-env-log = "0.2.8"
env_logger = "*"