[package]
name = "goldboot"
description = "A command-line application for building goldboot images"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Tyler Cook"]
readme = "README.md"
homepage = "https://goldboot.org"
repository = "https://github.com/goldboot/goldboot/"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.7", features = ["derive"] }
console = "0.15.7"
dialoguer = "0.11.0"
env_logger = "0"
fossable = "0.1.0"
hex = "0.4.3"
indicatif = "0.17.7"
log = { version = "0.4.20", default-features = false }
rand = "0.8.5"
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["stream", "blocking", "json"] }
rust-embed = "8.0.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_win_unattend = "0.1.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
simple-error = "0.3.0"
strum = { version = "0.25.0", features = ["derive"] }
tempfile = "3.8.1"
ubyte = "0.10.4"
url = { version = "2.4.1", features = ["serde"] }
validator = { version = "0.16.1", features = ["derive"] }
whoami = "1.4.1"

[dev-dependencies]
test-env-log = "0"
env_logger = "0"
