[package]
name = "goldboot"
description = "A command-line application for building goldboot images"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Tyler Cook"]
readme = "README.md"
homepage = "https://goldboot.org"
repository = "https://github.com/goldboot/goldboot/"

[dependencies]
block-utils = { version = "0.11.1", optional = true }
chrono = "0.4.31"
clap = { version = "4.4.16", features = ["derive"] }
console = "0.15.7"
dialoguer = "0.11.0"
env_logger = "0"
fossable = "0.1.2"
gdk4 = { version = "0.7.3", optional = true }
gdk-pixbuf = { version = "0.18.3", optional = true }
glib-macros = { version = "0.18.3", optional = true }
goldboot-image = { path="../goldboot-image", version = "0.0.1" }
goldboot-macros = { path="../goldboot-macros", version = "0.0.1" }
gtk4 = { version = "0.7.3", optional = true }
hex = "0.4.3"
indicatif = "0.17.7"
log = { version = "0.4.20", default-features = false }
png = "0.17.10"
rand = "0.8.5"
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["stream", "blocking", "json"] }
ron = "0.8.1"
serde = { version = "1.0.190", features = ["derive"] }
serde_win_unattend = "0.1.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
ssh2 = { version = "0.9.4", features = ["vendored-openssl"] } # TODO russh
strum = { version = "0.25.0", features = ["derive"] }
tempfile = "3.8.1"
ubyte = "0.10.4"
url = { version = "2.4.1", features = ["serde"] }
validator = { version = "0.16.1", features = ["derive"] }
vnc = "0.4.0"
whoami = "1.4.1"
zstd = "0.13.0"
enum_dispatch = "0.3.12"
serde_json = "1.0.108"
toml = "0.8.8"
serde_yaml = "0.9.27"
anyhow = "1.0.76"
byte-unit = "5.1.2"

[dev-dependencies]
test-env-log = "0"
env_logger = "0"

[features]
default = ["cast"]

# Support for the graphical UI
gui = ["dep:gtk4", "dep:glib-macros", "dep:gdk4", "dep:gdk-pixbuf", "dep:block-utils"]

# Support for casting images
cast = []
