name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          #sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y libudev-dev libgtk-4-dev
          #sudo apt-get install -y libudev-dev:arm64 libgtk-4-dev:arm64 openssl-dev:arm64

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build x86_64
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v3
        with:
          name: goldboot-x86_64-unknown-linux-gnu
          path: target/release/goldboot

      - uses: actions/upload-artifact@v3
        with:
          name: goldboot-registry-x86_64-unknown-linux-gnu
          path: target/release/goldboot-registry

      - uses: actions/upload-artifact@v3
        with:
          name: goldboot-linux-x86_64-unknown-linux-gnu
          path: target/release/goldboot-linux

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Disable goldboot-linux
        run: sed -i '' '/goldboot-linux/d' Cargo.toml

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build x86_64
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v3
        with:
          name: goldboot-x86_64-apple-darwin
          path: target/release/goldboot

      - uses: actions/upload-artifact@v3
        with:
          name: goldboot-registry-x86_64-apple-darwin
          path: target/release/goldboot-registry

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Disable goldboot-linux
        run: sed -i '/goldboot-linux/d' Cargo.toml

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build x86_64
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v3
        with:
          name: goldboot-x86_64-pc-windows-msvc
          path: target/release/goldboot

      - uses: actions/upload-artifact@v3
        with:
          name: goldboot-registry-x86_64-pc-windows-msvc
          path: target/release/goldboot-registry

  test-x86_64:
    name: Test ${{ matrix.profile }} x86_64
    runs-on: ubuntu-latest
    needs: build-linux
    strategy:
      fail-fast: false
      matrix:
        profile: [ArchLinux]
    steps:
      - name: Increase free space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Install goldboot
        uses: actions/download-artifact@v3
        with:
          name: goldboot-x86_64-unknown-linux-gnu
          path: /home/runner/.local/bin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86
          sudo mkdir -p /var/lib/goldboot/images
          sudo chmod -R 777 /var/lib/goldboot
          sudo chmod +x /home/runner/.local/bin/goldboot

      - name: Run goldboot
        run: |
          goldboot init --template ${{ matrix.profile }} --disk 16G
          goldboot build --record
          fallocate -l 16GiB disk.raw
          goldboot write --image ${{ matrix.profile }} --output disk.raw

      - name: Store debug output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Debug output
          path: './*/screenshots'
