name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libgtk-4-dev

      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          cargo build --target x86_64-unknown-linux-gnu

      - name: Store build output
        uses: actions/upload-artifact@v3
        with:
          name: build-x86_64
          path: target/x86_64-unknown-linux-gnu/debug/goldboot

  test-x86_64:
    name: Test ${{ matrix.profile }} x86_64
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        profile: [ArchLinux, Alpine, Windows10, MacOS]
    steps:
      - name: Increase free space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Install goldboot
        uses: actions/download-artifact@v3
        with:
          name: build-x86_64
          path: /home/runner/.local/bin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 ovmf
          sudo mkdir -p /var/lib/goldboot/images
          sudo chmod -R 777 /var/lib/goldboot
          sudo chmod +x /home/runner/.local/bin/goldboot

      - name: Run goldboot
        run: |
          goldboot init --profile ${{ matrix.profile }} --disk 16G
          goldboot build --record
          fallocate -l 16GiB disk.raw
          goldboot image write --image ${{ matrix.profile }} --disk disk.raw

      - name: Store debug output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Debug output
          path: './*/screenshots'

  test-aarch64:
    name: Test ${{ matrix.profile }} aarch64
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        profile: [ArchLinux]
    steps:
      - name: Increase free space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Install goldboot
        uses: actions/download-artifact@v3
        with:
          name: build-aarch64
          path: /home/runner/.local/bin

      - name: Install dependencies
        run: |
          sudo apt-get install -y qemu-system-aarch64 ovmf
          sudo mkdir -p /var/lib/goldboot/images
          sudo chmod -R 777 /var/lib/goldboot
          sudo chmod +x /home/runner/.local/bin/goldboot

      - name: Run goldboot
        run: |
          goldboot init --profile ${{ matrix.profile }} --arch aarch64 --disk 16G
          goldboot build --record
          fallocate -l 16GiB disk.raw
          goldboot image write --image ${{ matrix.profile }} --disk disk.raw

      - name: Store debug output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Debug output
          path: './*/screenshots'
