on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: .

      - name: Assemble release
        run: |
          ls -l
          mkdir release
          cp goldboot-x86_64-unknown-linux-gnu/goldboot release/goldboot-x86_64-unknown-linux-gnu
          cp goldboot-linux-x86_64-unknown-linux-gnu/goldboot-linux release/goldboot-linux-x86_64-unknown-linux-gnu

          cp goldboot-x86_64-apple-darwin/goldboot release/goldboot-x86_64-apple-darwin

          cp goldboot-x86_64-pc-windows-msvc/goldboot release/goldboot-x86_64-pc-windows-msvc

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
