on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: .

      - name: Assemble release
        run: |
          ls -l
          mkdir release
          #cp target/release/aarch64-unknown-linux-gnu/goldboot release/goldboot-aarch64-unknown-linux-gnu
          cp target/release/goldboot release/goldboot-x86_64-unknown-linux-gnu
          cp target/release/goldboot-gui release/goldboot-gui-x86_64-unknown-linux-gnu
          cp target/release/goldboot-registry release/goldboot-registry-x86_64-unknown-linux-gnu

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
