on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PACKER_LOG: 1
  GOLDBOOT_DEBUG: 1

jobs:
  linux-x86_64:
    name: Test Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 ovmf packer sshpass
          sudo mkdir -p /var/lib/goldboot/images
          sudo chmod -R 777 /var/lib/goldboot

      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and install
        run: |
          cargo build --target x86_64-unknown-linux-gnu
          sudo cp target/x86_64-unknown-linux-gnu/debug/goldboot /usr/bin

      - name: Test ArchLinux profile
        run: |
          mkdir ArchLinux && cd ArchLinux
          goldboot init --profile ArchLinux --disk 1G
          goldboot build --scale 2.5
          fallocate -l 1GiB /tmp/ArchLinux.raw
          goldboot image write --image ArchLinux --disk /tmp/ArchLinux.raw
